version: "3.8"
   
services:
  web:
    build: .
    command: python -m gunicorn --bind :3000 --chdir hab-main/ backend.wsgi:application --reload
    volumes:
      - static_volume:/hab-website/hab-main/staticfiles
    ports:
      - 8080:80

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/hab-website/hab-main/staticfiles
    ports:
      - 3000:80
    depends_on:
      - web

volumes:
  static_volume:
